apiVersion: batch/v1
kind: Job
metadata:
  name: checks
  labels:
    app: checks
spec:
  parallelism: 1    
  completions: 1    
  template:     
    metadata:
      name: checks
      labels:
        app: checks
    spec:
      containers:
      - name: checks
        image: 172.30.172.247:5000/certcheck/openshift-ansible
        imagePullPolicy: "Always"
        env:
        - name: PLAYBOOK_FILE
          value: playbooks/adhoc/cert_expiry_check.yaml
        - name: INVENTORY_URL
          value: http://192.168.55.1/hosts
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "False"
        - name: ANSIBLE_PRIVATE_KEY_FILE
          value: /opt/app-root/src/.ssh/id_rsa/ssh-privatekey
        - name: ANSIBLE_LOCAL_TEMP
          value: /tmp/certcheck
        - name: OPTS
          value: "-v"
        volumeMounts:
        - name: sshkey
          mountPath: /opt/app-root/src/.ssh/id_rsa
      volumes:
        - name: sshkey
          secret:
            secretName: sshkey
      restartPolicy: Never
